### ISSUE TITLE
Alchemy reactions randomization

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#245]
## Description
Each "reaction prototype" can have multiple results, e.g.:
```
- type: reaction
  id: CP14ExampleReaction
  reactants:
    CP14BloodGrassSap:
      amount: 0.5
    CP14WildSageSap:
      amount: 0.5
  products:
    CP14BasicEffectEmpty: 0.25
    CP14BasicEffectHealBrute: 0.25
  cp14RandomProducts:
    - CP14BasicEffectEmpty: 0.25
      CP14BasicEffectHealBrute: 0.25
    - CP14BasicEffectEmpty: 0.25
      CP14BasicEffectHealCold: 0.25
    - CP14BasicEffectEmpty: 0.25
      CP14BasicEffectHealHeat: 0.25
```

at the beginning of the round, if the reaction prototype has such additional outcome options, one of them must be chosen absolutely at random.

- Throughout the round, this reaction must generate the same result selected at the beginning of the round.
- The guidebook must also describe the result of the reaction selected in that round.
